//go:build go1.22

// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for CertType.
const (
	Client CertType = "client"
	Server CertType = "server"
)

// Valid indicates whether the value is a known member of the CertType enum.
func (e CertType) Valid() bool {
	switch e {
	case Client:
		return true
	case Server:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for KeyAlgorithm.
const (
	Ecdsa KeyAlgorithm = "ecdsa"
	Rsa   KeyAlgorithm = "rsa"
)

// Valid indicates whether the value is a known member of the KeyAlgorithm enum.
func (e KeyAlgorithm) Valid() bool {
	switch e {
	case Ecdsa:
		return true
	case Rsa:
		return true
	default:
		return false
	}
}

// CAChainResponse defines model for CAChainResponse.
type CAChainResponse struct {
	// ChainPem PEM bundle containing the Intermediate CA certificate followed by the Root CA certificate. Install this as a trusted CA anchor to validate certificates issued by this service.
	ChainPem *string `json:"chain_pem,omitempty"`
}

// CertListResponse Paginated list of certificate summaries.
type CertListResponse struct {
	// Certs The list of certificate summaries matching the query.
	Certs *[]Summary `json:"certs,omitempty"`

	// Total Total number of results in the current response (not the full dataset count).
	Total *int `json:"total,omitempty"`
}

// CertType Distinguishes TLS server certificates (for HTTPS/TLS) from client authentication certificates (for mTLS).
type CertType string

// ClientRequest Parameters for issuing a client authentication certificate.
type ClientRequest struct {
	// CommonName The identity of the client, used as the Certificate Subject Common Name (CN). Typically a username or service account name.
	CommonName string `json:"common_name"`

	// KeyAlgorithm Key algorithm to use when generating the certificate key pair. `ecdsa` uses ECDSA P-256; `rsa` uses RSA 2048. Defaults to `ecdsa`.
	KeyAlgorithm *KeyAlgorithm `json:"key_algorithm,omitempty"`

	// ValidityDays Number of days the certificate should be valid. Must be between 1 and 365 inclusive. Defaults to 90.
	ValidityDays *int `json:"validity_days,omitempty"`
}

// ConflictResponse Error response returned when a 409 Conflict occurs because an active certificate already exists for the requested common name and type.
type ConflictResponse struct {
	// Error Human-readable description of the conflict.
	Error *string `json:"error,omitempty"`

	// Serial Serial number of the existing conflicting certificate.
	Serial *string `json:"serial,omitempty"`
}

// ErrorResponse Standard error response body returned for all 4xx and 5xx responses.
type ErrorResponse struct {
	// Error Human-readable description of the error.
	Error *string `json:"error,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Service health status. Always `"ok"` when the service is running.
	Status *HealthResponseStatus `json:"status,omitempty"`
}

// HealthResponseStatus Service health status. Always `"ok"` when the service is running.
type HealthResponseStatus string

// IssuedCert The result of a successful certificate issuance. The `private_key_pem` field is populated exactly once in this response and is never stored by the service. The caller must persist it securely.
type IssuedCert struct {
	// CertificatePem PEM-encoded signed leaf certificate.
	CertificatePem *string `json:"certificate_pem,omitempty"`

	// ChainPem PEM bundle containing the Intermediate CA certificate followed by the Root CA certificate. Append this to the leaf certificate when configuring TLS to provide a complete trust chain.
	ChainPem *string `json:"chain_pem,omitempty"`

	// CommonName The Certificate Subject Common Name (CN).
	CommonName *string `json:"common_name,omitempty"`

	// ExpiresAt UTC timestamp when the certificate expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// IssuedAt UTC timestamp when the certificate was issued.
	IssuedAt *time.Time `json:"issued_at,omitempty"`

	// PrivateKeyPem PEM-encoded private key for the issued certificate. Returned exactly once at issuance. The service does not persist this value — the caller is solely responsible for storing it securely.
	PrivateKeyPem *string `json:"private_key_pem,omitempty"`

	// Serial Hex-encoded certificate serial number assigned by the CA.
	Serial *string `json:"serial,omitempty"`

	// Type Distinguishes TLS server certificates (for HTTPS/TLS) from client authentication certificates (for mTLS).
	Type *CertType `json:"type,omitempty"`
}

// IssuedCertStored A certificate record as returned from GET endpoints. Identical to `IssuedCert` except `private_key_pem` is always empty because the private key is never persisted after initial issuance.
type IssuedCertStored struct {
	// CertificatePem PEM-encoded signed leaf certificate.
	CertificatePem *string `json:"certificate_pem,omitempty"`

	// ChainPem PEM bundle containing the Intermediate CA certificate followed by the Root CA certificate.
	ChainPem *string `json:"chain_pem,omitempty"`

	// CommonName The Certificate Subject Common Name (CN).
	CommonName *string `json:"common_name,omitempty"`

	// ExpiresAt UTC timestamp when the certificate expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// IssuedAt UTC timestamp when the certificate was issued.
	IssuedAt *time.Time `json:"issued_at,omitempty"`

	// PrivateKeyPem Always empty on GET responses. The private key is never stored by the service and cannot be retrieved after initial issuance.
	PrivateKeyPem *string `json:"private_key_pem,omitempty"`

	// Serial Hex-encoded certificate serial number.
	Serial *string `json:"serial,omitempty"`

	// Type Distinguishes TLS server certificates (for HTTPS/TLS) from client authentication certificates (for mTLS).
	Type *CertType `json:"type,omitempty"`
}

// KeyAlgorithm Key algorithm to use when generating the certificate key pair. `ecdsa` uses ECDSA P-256; `rsa` uses RSA 2048. Defaults to `ecdsa`.
type KeyAlgorithm string

// ServerRequest Parameters for issuing a TLS server certificate. At least one of `dns_names` or `ip_addresses` must be provided.
type ServerRequest struct {
	// CommonName The Certificate Subject Common Name (CN). Typically the primary DNS name for the service.
	CommonName string `json:"common_name"`

	// DnsNames DNS Subject Alternative Names (SANs). At least one of `dns_names` or `ip_addresses` is required.
	DnsNames *[]string `json:"dns_names,omitempty"`

	// IpAddresses IP address Subject Alternative Names (SANs). At least one of `dns_names` or `ip_addresses` is required.
	IpAddresses *[]string `json:"ip_addresses,omitempty"`

	// KeyAlgorithm Key algorithm to use when generating the certificate key pair. `ecdsa` uses ECDSA P-256; `rsa` uses RSA 2048. Defaults to `ecdsa`.
	KeyAlgorithm *KeyAlgorithm `json:"key_algorithm,omitempty"`

	// ValidityDays Number of days the certificate should be valid. Must be between 1 and 365 inclusive. Defaults to 90.
	ValidityDays *int `json:"validity_days,omitempty"`
}

// Summary Lightweight projection of a certificate record used in list responses. Contains no PEM fields.
type Summary struct {
	// CommonName The Certificate Subject Common Name (CN).
	CommonName *string `json:"common_name,omitempty"`

	// ExpiresAt UTC timestamp when the certificate expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// IssuedAt UTC timestamp when the certificate was issued.
	IssuedAt *time.Time `json:"issued_at,omitempty"`

	// Serial Hex-encoded certificate serial number.
	Serial *string `json:"serial,omitempty"`

	// Type Distinguishes TLS server certificates (for HTTPS/TLS) from client authentication certificates (for mTLS).
	Type *CertType `json:"type,omitempty"`
}

// SerialPath defines model for SerialPath.
type SerialPath = string

// BadRequest Standard error response body returned for all 4xx and 5xx responses.
type BadRequest = ErrorResponse

// Conflict Error response returned when a 409 Conflict occurs because an active certificate already exists for the requested common name and type.
type Conflict = ConflictResponse

// InternalError Standard error response body returned for all 4xx and 5xx responses.
type InternalError = ErrorResponse

// NotFound Standard error response body returned for all 4xx and 5xx responses.
type NotFound = ErrorResponse

// ListCertsParams defines parameters for ListCerts.
type ListCertsParams struct {
	// Type Filter results to only server or client certificates.
	Type *CertType `form:"type,omitempty" json:"type,omitempty"`

	// Expired When `true`, include expired certificates in the results. Defaults to `false` (only active certificates are returned).
	Expired *bool `form:"expired,omitempty" json:"expired,omitempty"`

	// Limit Maximum number of results to return. Defaults to 100.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip for pagination. Defaults to 0.
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetCertByCNParams defines parameters for GetCertByCN.
type GetCertByCNParams struct {
	// Type The type of certificate to look up.
	Type CertType `form:"type" json:"type"`

	// Cn The common name (CN) of the certificate to look up.
	Cn string `form:"cn" json:"cn"`
}

// SignClientJSONRequestBody defines body for SignClient for application/json ContentType.
type SignClientJSONRequestBody = ClientRequest

// SignServerJSONRequestBody defines body for SignServer for application/json ContentType.
type SignServerJSONRequestBody = ServerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve the CA certificate chain
	// (GET /ca-chain)
	GetCAChain(w http.ResponseWriter, r *http.Request)
	// List issued certificates
	// (GET /certs)
	ListCerts(w http.ResponseWriter, r *http.Request, params ListCertsParams)
	// Look up a certificate by common name
	// (GET /certs/by-cn)
	GetCertByCN(w http.ResponseWriter, r *http.Request, params GetCertByCNParams)
	// Delete a certificate record
	// (DELETE /certs/{serial})
	DeleteCert(w http.ResponseWriter, r *http.Request, serial SerialPath)
	// Get a certificate by serial number
	// (GET /certs/{serial})
	GetCert(w http.ResponseWriter, r *http.Request, serial SerialPath)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Issue a client authentication certificate
	// (POST /sign/client)
	SignClient(w http.ResponseWriter, r *http.Request)
	// Issue a TLS server certificate
	// (POST /sign/server)
	SignServer(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCAChain operation middleware
func (siw *ServerInterfaceWrapper) GetCAChain(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCAChain(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCerts operation middleware
func (siw *ServerInterfaceWrapper) ListCerts(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCertsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "expired" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "expired", r.URL.Query(), &params.Expired, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "expired", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCerts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCertByCN operation middleware
func (siw *ServerInterfaceWrapper) GetCertByCN(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCertByCNParams

	// ------------- Required query parameter "type" -------------

	if paramValue := r.URL.Query().Get("type"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Required query parameter "cn" -------------

	if paramValue := r.URL.Query().Get("cn"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cn"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "cn", r.URL.Query(), &params.Cn, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cn", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCertByCN(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCert operation middleware
func (siw *ServerInterfaceWrapper) DeleteCert(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serial" -------------
	var serial SerialPath

	err = runtime.BindStyledParameterWithOptions("simple", "serial", r.PathValue("serial"), &serial, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serial", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCert(w, r, serial)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCert operation middleware
func (siw *ServerInterfaceWrapper) GetCert(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serial" -------------
	var serial SerialPath

	err = runtime.BindStyledParameterWithOptions("simple", "serial", r.PathValue("serial"), &serial, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serial", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCert(w, r, serial)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignClient operation middleware
func (siw *ServerInterfaceWrapper) SignClient(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignClient(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignServer operation middleware
func (siw *ServerInterfaceWrapper) SignServer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignServer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/ca-chain", wrapper.GetCAChain)
	m.HandleFunc("GET "+options.BaseURL+"/certs", wrapper.ListCerts)
	m.HandleFunc("GET "+options.BaseURL+"/certs/by-cn", wrapper.GetCertByCN)
	m.HandleFunc("DELETE "+options.BaseURL+"/certs/{serial}", wrapper.DeleteCert)
	m.HandleFunc("GET "+options.BaseURL+"/certs/{serial}", wrapper.GetCert)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc("POST "+options.BaseURL+"/sign/client", wrapper.SignClient)
	m.HandleFunc("POST "+options.BaseURL+"/sign/server", wrapper.SignServer)

	return m
}
